export { default as PlayIcon } from "./play.svg";
export { default as BackIcon } from "./back.svg";
export { default as ForwardIcon } from "./forward.svg";
export { default as PlusIcon } from "./plus.svg";
export { default as PauseIcon } from "./pause.svg";
export { default as RepeatIcon } from "./repeat.svg";
export { default as ShuffleIcon } from "./shuffle.svg";
export { default as VolumeOffIcon } from "./volume-off.svg";
export { default as VolumeOnIcon } from "./volume-on.svg";
